(ns clojure-shadcn.stories.helpers.bridge-gen
  "shadow-cljs :build-hooks handler that auto-generates ESM bridge files
   for Storybook after every :stories compile.

   Storybook 10's CSF indexer needs literal `export default { ... }` metadata,
   while compiled CLJS story modules export `default` as a symbol reference.
   This hook reads each compiled *_stories.js module, extracts title/parameters
   from its cljs-runtime namespace file, extracts named exports from the ESM
   module, and writes a minimal bridge in stories/js/.

   Developers only write CLJS — the JS bridges are generated artifacts.

   Ported from the chatbot project (studio.stories.helpers.bridge-gen)."
  (:refer-clojure :exclude [flush])
  (:require [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- kebab-case
  "Convert dots and underscores to hyphens: clojure_shadcn.stories.foo_bar → clojure_shadcn-stories-foo-bar"
  [s]
  (-> s (str/replace #"[._]" "-")))

(defn- extract-title
  "Extract Storybook title from the compiled CJS default$ assignment."
  [content]
  (let [m (re-find #"\.default\$\s*=\s*\(\{[^}]*\"title\":\s*\"([^\"]+)\"" content)]
    (second m)))

(defn- extract-parameters
  "Extract Storybook parameters from the compiled CJS default$ assignment."
  [content]
  (let [m (re-find #"\.default\$\s*=\s*\(\{[^}]*\"parameters\":\s*\(\{([^}]*)\}" content)]
    (when-let [params-str (second m)]
      ;; Parse simple key-value pairs like "layout": "fullscreen"
      (into {}
            (for [[_ k v] (re-seq #"\"(\w+)\":\s*\"([^\"]+)\"" params-str)]
              [k v])))))

(defn- extract-exports
  "Extract named story exports from ESM `export let X = ...` lines."
  [content]
  (->> (re-seq #"export\s+(?:let|const|var|function)\s+(\w+)" content)
       (map second)
       (remove #(= % "default"))
       vec))

(defn- generate-bridge
  "Generate an ESM bridge file string for a single compiled CJS story file."
  [cjs-filename title parameters exports]
  (let [params-obj (if (seq parameters)
                     (str "{ "
                          (str/join ", " (map (fn [[k v]] (str k ": '" v "'")) parameters))
                          " }")
                     "{}")]
    (str "// Auto-generated by clojure-shadcn.stories.helpers.bridge-gen — do not edit.\n"
         "// Source: cljs-stories/" cjs-filename "\n"
         "import * as cljs from '../../cljs-stories/" cjs-filename "';\n"
         "\n"
         "export default {\n"
         "  title: '" title "',\n"
         "  parameters: " params-obj ",\n"
         "};\n"
         "\n"
         (str/join "\n" (map (fn [e] (str "export const " e " = cljs." e ";")) exports))
         "\n")))

(defn- process-story-file!
  "Read a compiled ESM story module and write its Storybook bridge."
  [^java.io.File module-file runtime-dir output-dir]
  (let [filename        (.getName module-file)
        module-content  (slurp module-file)
        runtime-file    (io/file runtime-dir filename)
        runtime-content (when (.exists runtime-file) (slurp runtime-file))
        title           (some-> runtime-content extract-title)
        params          (some-> runtime-content extract-parameters)
        exports         (extract-exports module-content)]
    (when (and title (seq exports))
      (let [bridge-name (str (kebab-case (str/replace filename #"\.js$" "")) ".stories.js")
            bridge-file (io/file output-dir bridge-name)
            bridge-code (generate-bridge filename title params exports)]
        (.mkdirs (io/file output-dir))
        (spit bridge-file bridge-code)
        (println (str "  [bridge-gen] " bridge-name " ← " filename
                      " (" (count exports) " stories)"))))))

(defn generate-all!
  "Scan cljs-stories/ for *_stories.js modules and generate bridges in stories/js/."
  []
  (let [cljs-dir    (io/file "cljs-stories")
        runtime-dir (io/file cljs-dir "cljs-runtime")
        output-dir  (io/file "stories" "js")
        story-files (->> (.listFiles cljs-dir)
                         (filter #(str/ends-with? (.getName %) "_stories.js")))]
    (println (str "[bridge-gen] Generating " (count story-files) " bridge(s)..."))
    (doseq [f story-files]
      (process-story-file! f runtime-dir output-dir))
    (println "[bridge-gen] Done.")))

;; ── shadow-cljs build hook API ──────────────────────────────────────────────
;; shadow-cljs calls these with (build-state & extra-args).
;; We only care about :flush (after files are written to disk).

(defn flush
  "Called by shadow-cljs after writing compiled JS to cljs-stories/.
   Regenerates the ESM bridge files for Storybook."
  {:shadow.build/stage :flush}
  [build-state & _]
  (generate-all!)
  build-state)
