(ns clojure-shadcn.stories.helpers.bridge-gen
  "shadow-cljs :build-hooks handler that auto-generates ESM bridge files
   for Storybook after every :stories compile.

   The compiled CJS files in cljs-stories/ can't be statically indexed by
   Storybook 10's CSF parser.  This hook reads each *_stories.js file,
   extracts the title and named exports, and writes a minimal ESM bridge
   into stories/js/ that Storybook's indexer can parse.

   Developers only write CLJS — the JS bridges are generated artifacts.

   Ported from the chatbot project (studio.stories.helpers.bridge-gen)."
  (:refer-clojure :exclude [flush])
  (:require [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- kebab-case
  "Convert dots and underscores to hyphens: clojure_shadcn.stories.foo_bar → clojure_shadcn-stories-foo-bar"
  [s]
  (-> s (str/replace #"[._]" "-")))

(defn- extract-title
  "Extract Storybook title from the compiled CJS default$ assignment."
  [content]
  (let [m (re-find #"\.default\$\s*=\s*\(\{[^}]*\"title\":\s*\"([^\"]+)\"" content)]
    (second m)))

(defn- extract-parameters
  "Extract Storybook parameters from the compiled CJS default$ assignment."
  [content]
  (let [m (re-find #"\.default\$\s*=\s*\(\{[^}]*\"parameters\":\s*\(\{([^}]*)\}" content)]
    (when-let [params-str (second m)]
      ;; Parse simple key-value pairs like "layout": "fullscreen"
      (into {}
            (for [[_ k v] (re-seq #"\"(\w+)\":\s*\"([^\"]+)\"" params-str)]
              [k v])))))

(defn- extract-exports
  "Extract named story exports from Object.defineProperty(module.exports, ...) lines."
  [content]
  (->> (re-seq #"Object\.defineProperty\(module\.exports,\s*\"(\w+)\"" content)
       (map second)
       (remove #(= % "default"))
       vec))

(defn- generate-bridge
  "Generate an ESM bridge file string for a single compiled CJS story file."
  [cjs-filename title parameters exports]
  (let [params-obj (if (seq parameters)
                     (str "{ "
                          (str/join ", " (map (fn [[k v]] (str k ": '" v "'")) parameters))
                          " }")
                     "{}")]
    (str "// Auto-generated by clojure-shadcn.stories.helpers.bridge-gen — do not edit.\n"
         "// Source: cljs-stories/" cjs-filename "\n"
         "import cljs from '../../cljs-stories/" cjs-filename "';\n"
         "\n"
         "export default {\n"
         "  title: '" title "',\n"
         "  parameters: " params-obj ",\n"
         "};\n"
         "\n"
         (str/join "\n" (map (fn [e] (str "export const " e " = cljs." e ";")) exports))
         "\n")))

(defn- process-story-file!
  "Read a compiled CJS story file and write its ESM bridge."
  [^java.io.File f output-dir]
  (let [filename  (.getName f)
        content   (slurp f)
        title     (extract-title content)
        params    (extract-parameters content)
        exports   (extract-exports content)]
    (when (and title (seq exports))
      (let [bridge-name (str (kebab-case (str/replace filename #"\.js$" "")) ".stories.js")
            bridge-file (io/file output-dir bridge-name)
            bridge-code (generate-bridge filename title params exports)]
        (.mkdirs (io/file output-dir))
        (spit bridge-file bridge-code)
        (println (str "  [bridge-gen] " bridge-name " ← " filename
                      " (" (count exports) " stories)"))))))

(defn- ensure-commonjs-marker!
  "Write cljs-stories/package.json with {\"type\": \"commonjs\"}.

   The repo root package.json declares \"type\": \"module\", which would make
   Vite/esbuild treat the shadow-cljs :npm-module output (CJS) as ESM —
   no default export gets synthesized from module.exports and every story
   fails with \"does not provide an export named 'default'\".  This marker
   overrides the module type for the cljs-stories/ subtree."
  [cljs-dir]
  (let [marker (io/file cljs-dir "package.json")]
    (when-not (.exists marker)
      (spit marker "{ \"type\": \"commonjs\" }\n")
      (println "[bridge-gen] Wrote cljs-stories/package.json (type: commonjs)"))))

(defn generate-all!
  "Scan cljs-stories/ for *_stories.js files and generate bridges in stories/js/."
  []
  (let [cljs-dir   (io/file "cljs-stories")
        output-dir (io/file "stories" "js")
        story-files (->> (.listFiles cljs-dir)
                         (filter #(str/ends-with? (.getName %) "_stories.js")))]
    (ensure-commonjs-marker! cljs-dir)
    (println (str "[bridge-gen] Generating " (count story-files) " bridge(s)..."))
    (doseq [f story-files]
      (process-story-file! f output-dir))
    (println "[bridge-gen] Done.")))

;; ── shadow-cljs build hook API ──────────────────────────────────────────────
;; shadow-cljs calls these with (build-state & extra-args).
;; We only care about :flush (after files are written to disk).

(defn flush
  "Called by shadow-cljs after writing compiled JS to cljs-stories/.
   Regenerates the ESM bridge files for Storybook."
  {:shadow.build/stage :flush}
  [build-state & _]
  (generate-all!)
  build-state)
