#!/usr/bin/env bb
;; Generates the :modules override required by shadow-cljs's :esm target.
;;
;; Story namespaces and their ^:export vars are the source of truth. This
;; avoids manually duplicating module definitions in shadow-cljs.edn.
;;
;; Usage: bb scripts/generate_story_modules.clj

(require '[clojure.java.io :as io]
         '[clojure.string :as str]
         '[clojure.pprint :as pprint])

(def stories-dir "stories/cljs/clojure_shadcn/stories")
(def output-file "target/story-modules.edn")
(def preferred-default-ns 'clojure-shadcn.stories.intro-stories)

(defn- story-namespaces
  []
  (->> (.listFiles (io/file stories-dir))
       (filter #(.isFile ^java.io.File %))
       (filter #(str/ends-with? (.getName ^java.io.File %) "_stories.cljs"))
       (sort-by #(.getName ^java.io.File %))
       (map (fn [file]
              (let [content (slurp file)
                    ns-match (re-find #"(?m)^\(ns\s+([^\s\)]+)" content)
                    ns-sym (some-> ns-match second symbol)
                    exports (->> (re-seq #"(?m)^\(defn?\s+\^:export\s+([A-Za-z0-9_$-]+)" content)
                                 (mapv #(symbol (second %))))]
                (when-not ns-sym
                  (throw (ex-info "Story source has no namespace declaration"
                                  {:file (.getPath ^java.io.File file)})))
                (when-not (some #{'default} exports)
                  (throw (ex-info "Story source must export default metadata"
                                  {:file (.getPath ^java.io.File file)
                                   :namespace ns-sym})))
                (when (< (count exports) 2)
                  (throw (ex-info "Story source must export at least one scene"
                                  {:file (.getPath ^java.io.File file)
                                   :namespace ns-sym})))
                {:ns ns-sym :exports exports})))))

(defn- module-key
  [ns-sym]
  (keyword (str/replace (str ns-sym) "-" "_")))

(defn- module-config
  [stories]
  (let [default-ns (if (some #(= preferred-default-ns (:ns %)) stories)
                     preferred-default-ns
                     (:ns (first stories)))
        default-key (module-key default-ns)]
    {:modules
     (into (sorted-map)
           (map (fn [{:keys [ns exports]}]
                  (let [key (module-key ns)]
                    [key (cond-> {:entries [ns]
                                  :exports (into {}
                                                 (map (fn [export]
                                                        [export (symbol (str ns "/" export))])
                                                      exports))}
                           (= key default-key) (assoc :default true)
                           (not= key default-key) (assoc :depends-on #{default-key}))]))
                stories))}))

(let [stories (vec (story-namespaces))
      config (module-config stories)
      output (io/file output-file)]
  (.mkdirs (.getParentFile output))
  (with-open [writer (io/writer output)]
    (binding [*out* writer]
      (println ";; Auto-generated by scripts/generate_story_modules.clj — do not edit.")
      (pprint/pprint config)))
  (println (str "[story-modules] Wrote " output-file " for " (count stories) " story namespaces.")))
